import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const html=readFileSync(new URL('triage.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const pure=script.slice(script.indexOf('function localToday'),script.indexOf('function read('));
const context={URL,Date};vm.createContext(context);vm.runInContext(pure,context);
const job={url:'https://example.com/job',title:'Senior Financial Analyst',location:'Sacramento, CA'};
assert.equal(context.roleFamily(job),'Finance & accounting');
assert.equal(context.roleFamily({title:'Buyer II'}),'Purchasing');
assert.equal(context.matches(job,null,{view:'active',lane:'',arrangement:'',search:''}),true);
assert.equal(context.matches(job,'dismissed',{view:'active',lane:'',arrangement:'',search:''}),false);
assert.equal(context.matches({...job,salary:'$20,000'},null,{view:'active',lane:'',arrangement:'',search:''}),true);
assert.equal(context.matches({...job,location:'Remote, US'},null,{view:'active',lane:'',arrangement:'remote',search:''}),true);
assert.equal(context.safeURL('javascript:alert(1)'),null);
assert.equal(context.decodeJobs([{...job,url:'javascript:alert(1)'},job]).length,1);
assert.equal(context.decodeJobs([{...job,california_eligibility:'excluded'}]).length,0);
const now=Date.parse('2026-09-08T19:00:00Z');
assert.equal(context.recentEnough({date_posted:'2026-08-25'},now),true);
assert.equal(context.recentEnough({date_posted:'2026-08-24'},now),false);
assert.equal(context.recentEnough({date_posted:'2026-08-24T15:00:00Z'},now),false);
assert.equal(context.recentEnough({date_posted:'Posted 15 Days Ago'},now),false);
assert.equal(context.recentEnough({date_posted:'Posted 14 Days Ago'},now),true);
assert.equal(context.recentEnough({date_posted:'unknown'},now),true);
assert.equal(context.recentEnough({},now),true);
assert.equal(context.decodeJobs([{...job,date_posted:'2000-01-01'}]).length,0);
assert(html.includes("' · Last attempt: '+(s.last_attempt||'Never')"));
assert.throws(()=>context.validDecisions({'https://example.com':{s:'unknown',t:1}}));
assert.equal(context.mergeDecisions({a:{s:'saved',t:2}},{a:{s:'dismissed',t:1}}).a.s,'saved');
assert.equal(context.mergeDecisions({a:{s:'saved',t:1}},{a:{s:null,t:2}}).a.s,null);
assert(!/pjTriage|jackieTriage|SYNC_URL|scores\.json|hollywood_jobs/.test(html));
assert.deepEqual([...html.matchAll(/fetch\('([^']+)'/g)].map(m=>m[1]),['all_jobs.json','source_status.json']);
assert(html.includes("data.owner!=='eli'"));
console.log('Dashboard behavior, isolation, safety and syntax checks passed');
